# Generated by Django 3.1.2 on 2022-03-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vocabulary',
            new_name='Words',
        ),
    ]
