# Generated by Django 3.1.2 on 2022-03-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor_api', '0002_auto_20220304_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Keywords',
        ),
        migrations.RenameField(
            model_name='keywords',
            old_name='word',
            new_name='keyword',
        ),
    ]
